name: Run ZAP test
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://pabloqr-calculadora-frontend.azurewebsites.net'
          cmd_options: '-a'
